<?php

/*
 * This file is part of the package wapplersystems/blog.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

// Alte Klassennamen aus t3g/blog und t3bootstrap_blog, damit Fremdcode
// (z. B. linear/linear BlogArticleProcessor) ohne Anpassung weiterlaeuft.
return [
    'T3Bootstrap\Blog\Controller\PostController' => 'WapplerSystems\Blog\Controller\PostController',
    'T3Bootstrap\Blog\DataProcessing\FeaturedImageProcessor' => 'WapplerSystems\Blog\DataProcessing\FeaturedImageProcessor',
    'T3Bootstrap\Blog\Domain\Factory\CommentFormFactory' => 'WapplerSystems\Blog\Domain\Factory\FrontendUserCommentFormFactory',
    'T3Bootstrap\Blog\Domain\Finisher\CommentFormFinisher' => 'WapplerSystems\Blog\Domain\Finisher\FrontendUserCommentFormFinisher',
    'T3Bootstrap\Blog\Domain\Model\Comment' => 'WapplerSystems\Blog\Domain\Model\Comment',
    'T3Bootstrap\Blog\Domain\Model\FrontendUser' => 'WapplerSystems\Blog\Domain\Model\FrontendUser',
    'T3Bootstrap\Blog\Domain\Repository\FrontendUserRepository' => 'WapplerSystems\Blog\Domain\Repository\FrontendUserRepository',
    'T3Bootstrap\Blog\Pagination\CustomAbstractPaginator' => 'WapplerSystems\Blog\Pagination\CustomAbstractPaginator',
    'T3Bootstrap\Blog\Pagination\QueryResultPaginator' => 'WapplerSystems\Blog\Pagination\QueryResultPaginator',
    'T3G\AgencyPack\Blog\AvatarProvider\AvatarProviderInterface' => 'WapplerSystems\Blog\AvatarProvider\AvatarProviderInterface',
    'T3G\AgencyPack\Blog\AvatarProvider\GravatarProvider' => 'WapplerSystems\Blog\AvatarProvider\GravatarProvider',
    'T3G\AgencyPack\Blog\AvatarProvider\ImageProvider' => 'WapplerSystems\Blog\AvatarProvider\ImageProvider',
    'T3G\AgencyPack\Blog\Backend\FormDataProvider\CategoryDefaultValueProvider' => 'WapplerSystems\Blog\Backend\FormDataProvider\CategoryDefaultValueProvider',
    'T3G\AgencyPack\Blog\Backend\View\BlogPostHeaderContentRenderer' => 'WapplerSystems\Blog\Backend\View\BlogPostHeaderContentRenderer',
    'T3G\AgencyPack\Blog\Constants' => 'WapplerSystems\Blog\Constants',
    'T3G\AgencyPack\Blog\Controller\BackendController' => 'WapplerSystems\Blog\Controller\BackendController',
    'T3G\AgencyPack\Blog\Controller\CommentController' => 'WapplerSystems\Blog\Controller\CommentController',
    'T3G\AgencyPack\Blog\Controller\PostController' => 'WapplerSystems\Blog\Controller\PostController',
    'T3G\AgencyPack\Blog\Controller\WidgetController' => 'WapplerSystems\Blog\Controller\WidgetController',
    'T3G\AgencyPack\Blog\DataProcessing\FeaturedImageProcessor' => 'WapplerSystems\Blog\DataProcessing\FeaturedImageProcessor',
    'T3G\AgencyPack\Blog\DataTransferObject\AvatarResource' => 'WapplerSystems\Blog\DataTransferObject\AvatarResource',
    'T3G\AgencyPack\Blog\DataTransferObject\Gravatar' => 'WapplerSystems\Blog\DataTransferObject\Gravatar',
    'T3G\AgencyPack\Blog\DataTransferObject\PostRepositoryDemand' => 'WapplerSystems\Blog\DataTransferObject\PostRepositoryDemand',
    'T3G\AgencyPack\Blog\Domain\Factory\CommentFormFactory' => 'WapplerSystems\Blog\Domain\Factory\CommentFormFactory',
    'T3G\AgencyPack\Blog\Domain\Factory\FrontendUserCommentFormFactory' => 'WapplerSystems\Blog\Domain\Factory\FrontendUserCommentFormFactory',
    'T3G\AgencyPack\Blog\Domain\Finisher\CommentFormFinisher' => 'WapplerSystems\Blog\Domain\Finisher\CommentFormFinisher',
    'T3G\AgencyPack\Blog\Domain\Finisher\FrontendUserCommentFormFinisher' => 'WapplerSystems\Blog\Domain\Finisher\FrontendUserCommentFormFinisher',
    'T3G\AgencyPack\Blog\Domain\Model\Author' => 'WapplerSystems\Blog\Domain\Model\Author',
    'T3G\AgencyPack\Blog\Domain\Model\Category' => 'WapplerSystems\Blog\Domain\Model\Category',
    'T3G\AgencyPack\Blog\Domain\Model\Comment' => 'WapplerSystems\Blog\Domain\Model\Comment',
    'T3G\AgencyPack\Blog\Domain\Model\Content' => 'WapplerSystems\Blog\Domain\Model\Content',
    'T3G\AgencyPack\Blog\Domain\Model\FrontendUser' => 'WapplerSystems\Blog\Domain\Model\FrontendUser',
    'T3G\AgencyPack\Blog\Domain\Model\Post' => 'WapplerSystems\Blog\Domain\Model\Post',
    'T3G\AgencyPack\Blog\Domain\Model\Tag' => 'WapplerSystems\Blog\Domain\Model\Tag',
    'T3G\AgencyPack\Blog\Domain\Repository\AuthorRepository' => 'WapplerSystems\Blog\Domain\Repository\AuthorRepository',
    'T3G\AgencyPack\Blog\Domain\Repository\CategoryRepository' => 'WapplerSystems\Blog\Domain\Repository\CategoryRepository',
    'T3G\AgencyPack\Blog\Domain\Repository\CommentRepository' => 'WapplerSystems\Blog\Domain\Repository\CommentRepository',
    'T3G\AgencyPack\Blog\Domain\Repository\FrontendUserRepository' => 'WapplerSystems\Blog\Domain\Repository\FrontendUserRepository',
    'T3G\AgencyPack\Blog\Domain\Repository\PostRepository' => 'WapplerSystems\Blog\Domain\Repository\PostRepository',
    'T3G\AgencyPack\Blog\Domain\Repository\TagRepository' => 'WapplerSystems\Blog\Domain\Repository\TagRepository',
    'T3G\AgencyPack\Blog\Domain\Validator\GoogleCaptchaValidator' => 'WapplerSystems\Blog\Domain\Validator\GoogleCaptchaValidator',
    'T3G\AgencyPack\Blog\ExpressionLanguage\BlogFunctionsProvider' => 'WapplerSystems\Blog\ExpressionLanguage\BlogFunctionsProvider',
    'T3G\AgencyPack\Blog\ExpressionLanguage\ConditionProvider' => 'WapplerSystems\Blog\ExpressionLanguage\ConditionProvider',
    'T3G\AgencyPack\Blog\ExpressionLanguage\CurrentPageProvider' => 'WapplerSystems\Blog\ExpressionLanguage\CurrentPageProvider',
    'T3G\AgencyPack\Blog\Factory\PostRepositoryDemandFactory' => 'WapplerSystems\Blog\Factory\PostRepositoryDemandFactory',
    'T3G\AgencyPack\Blog\Fractor\V14\MigrateTypoScriptBlogIsPageExpressionFractor' => 'WapplerSystems\Blog\Fractor\V14\MigrateTypoScriptBlogIsPageExpressionFractor',
    'T3G\AgencyPack\Blog\Fractor\V14\MigrateTypoScriptBlogIsPostExpressionFractor' => 'WapplerSystems\Blog\Fractor\V14\MigrateTypoScriptBlogIsPostExpressionFractor',
    'T3G\AgencyPack\Blog\Hooks\CreateSiteConfigurationHook' => 'WapplerSystems\Blog\Hooks\CreateSiteConfigurationHook',
    'T3G\AgencyPack\Blog\Hooks\DataHandlerHook' => 'WapplerSystems\Blog\Hooks\DataHandlerHook',
    'T3G\AgencyPack\Blog\Listener\ModifyPageLayoutContent' => 'WapplerSystems\Blog\Listener\ModifyPageLayoutContent',
    'T3G\AgencyPack\Blog\Listener\RenderAdditionalContentToRecordList' => 'WapplerSystems\Blog\Listener\RenderAdditionalContentToRecordList',
    'T3G\AgencyPack\Blog\Mail\MailContent' => 'WapplerSystems\Blog\Mail\MailContent',
    'T3G\AgencyPack\Blog\Notification\AbstractNotification' => 'WapplerSystems\Blog\Notification\AbstractNotification',
    'T3G\AgencyPack\Blog\Notification\CommentAddedNotification' => 'WapplerSystems\Blog\Notification\CommentAddedNotification',
    'T3G\AgencyPack\Blog\Notification\NotificationInterface' => 'WapplerSystems\Blog\Notification\NotificationInterface',
    'T3G\AgencyPack\Blog\Notification\NotificationManager' => 'WapplerSystems\Blog\Notification\NotificationManager',
    'T3G\AgencyPack\Blog\Notification\Processor\ProcessorInterface' => 'WapplerSystems\Blog\Notification\Processor\ProcessorInterface',
    'T3G\AgencyPack\Blog\Pagination\BlogPagination' => 'WapplerSystems\Blog\Pagination\BlogPagination',
    'T3G\AgencyPack\Blog\Pagination\CustomAbstractPaginator' => 'WapplerSystems\Blog\Pagination\CustomAbstractPaginator',
    'T3G\AgencyPack\Blog\Pagination\QueryResultPaginator' => 'WapplerSystems\Blog\Pagination\QueryResultPaginator',
    'T3G\AgencyPack\Blog\Routing\Aspect\StaticDatabaseMapper' => 'WapplerSystems\Blog\Routing\Aspect\StaticDatabaseMapper',
    'T3G\AgencyPack\Blog\Service\Avatar\AvatarResourceResolverInterface' => 'WapplerSystems\Blog\Service\Avatar\AvatarResourceResolverInterface',
    'T3G\AgencyPack\Blog\Service\Avatar\Gravatar\GravatarResourceResolver' => 'WapplerSystems\Blog\Service\Avatar\Gravatar\GravatarResourceResolver',
    'T3G\AgencyPack\Blog\Service\Avatar\Gravatar\GravatarUriBuilder' => 'WapplerSystems\Blog\Service\Avatar\Gravatar\GravatarUriBuilder',
    'T3G\AgencyPack\Blog\Service\Avatar\Gravatar\GravatarUriBuilderInterface' => 'WapplerSystems\Blog\Service\Avatar\Gravatar\GravatarUriBuilderInterface',
    'T3G\AgencyPack\Blog\Service\CacheService' => 'WapplerSystems\Blog\Service\CacheService',
    'T3G\AgencyPack\Blog\Service\CommentService' => 'WapplerSystems\Blog\Service\CommentService',
    'T3G\AgencyPack\Blog\Service\MetaTagService' => 'WapplerSystems\Blog\Service\MetaTagService',
    'T3G\AgencyPack\Blog\Service\SetupService' => 'WapplerSystems\Blog\Service\SetupService',
    'T3G\AgencyPack\Blog\TitleTagProvider\BlogTitleTagProvider' => 'WapplerSystems\Blog\TitleTagProvider\BlogTitleTagProvider',
    'T3G\AgencyPack\Blog\Updates\AbstractUpdate' => 'WapplerSystems\Blog\Updates\AbstractUpdate',
    'T3G\AgencyPack\Blog\Updates\AuthorSlugUpdate' => 'WapplerSystems\Blog\Updates\AuthorSlugUpdate',
    'T3G\AgencyPack\Blog\Updates\AvatarProviderUpdate' => 'WapplerSystems\Blog\Updates\AvatarProviderUpdate',
    'T3G\AgencyPack\Blog\Updates\CategorySlugUpdate' => 'WapplerSystems\Blog\Updates\CategorySlugUpdate',
    'T3G\AgencyPack\Blog\Updates\CategoryTypeUpdate' => 'WapplerSystems\Blog\Updates\CategoryTypeUpdate',
    'T3G\AgencyPack\Blog\Updates\CommentStatusUpdate' => 'WapplerSystems\Blog\Updates\CommentStatusUpdate',
    'T3G\AgencyPack\Blog\Updates\Criteria\AbstractCriteria' => 'WapplerSystems\Blog\Updates\Criteria\AbstractCriteria',
    'T3G\AgencyPack\Blog\Updates\Criteria\CriteriaInterface' => 'WapplerSystems\Blog\Updates\Criteria\CriteriaInterface',
    'T3G\AgencyPack\Blog\Updates\Criteria\EqualIntCriteria' => 'WapplerSystems\Blog\Updates\Criteria\EqualIntCriteria',
    'T3G\AgencyPack\Blog\Updates\Criteria\EqualStringCriteria' => 'WapplerSystems\Blog\Updates\Criteria\EqualStringCriteria',
    'T3G\AgencyPack\Blog\Updates\Criteria\InCriteria' => 'WapplerSystems\Blog\Updates\Criteria\InCriteria',
    'T3G\AgencyPack\Blog\Updates\Criteria\IsNullCriteria' => 'WapplerSystems\Blog\Updates\Criteria\IsNullCriteria',
    'T3G\AgencyPack\Blog\Updates\Criteria\NotEqualIntCriteria' => 'WapplerSystems\Blog\Updates\Criteria\NotEqualIntCriteria',
    'T3G\AgencyPack\Blog\Updates\DatabaseMonthYearUpdate' => 'WapplerSystems\Blog\Updates\DatabaseMonthYearUpdate',
    'T3G\AgencyPack\Blog\Updates\DatabasePublishDateUpdate' => 'WapplerSystems\Blog\Updates\DatabasePublishDateUpdate',
    'T3G\AgencyPack\Blog\Updates\FeaturedImageUpdate' => 'WapplerSystems\Blog\Updates\FeaturedImageUpdate',
    'T3G\AgencyPack\Blog\Updates\ListTypeMigration' => 'WapplerSystems\Blog\Updates\ListTypeMigration',
    'T3G\AgencyPack\Blog\Updates\TagSlugUpdate' => 'WapplerSystems\Blog\Updates\TagSlugUpdate',
    'T3G\AgencyPack\Blog\Utility\ArchiveUtility' => 'WapplerSystems\Blog\Utility\ArchiveUtility',
    'T3G\AgencyPack\Blog\Utility\SchemaUtility' => 'WapplerSystems\Blog\Utility\SchemaUtility',
    'T3G\AgencyPack\Blog\Utility\Socials\MastodonUtility' => 'WapplerSystems\Blog\Utility\Socials\MastodonUtility',
    'T3G\AgencyPack\Blog\Utility\Socials\TwitterXUtility' => 'WapplerSystems\Blog\Utility\Socials\TwitterXUtility',
    'T3G\AgencyPack\Blog\ViewHelpers\CacheViewHelper' => 'WapplerSystems\Blog\ViewHelpers\CacheViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Data\ContentListOptionsViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Data\ContentListOptionsViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Format\Nl2pViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Format\Nl2pViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\GravatarViewHelper' => 'WapplerSystems\Blog\ViewHelpers\GravatarViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\ArchiveViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\ArchiveViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\AuthorViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\AuthorViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\Be\AuthorViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\Be\AuthorViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\Be\CategoryViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\Be\CategoryViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\Be\CommentViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\Be\CommentViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\Be\PostViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\Be\PostViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\Be\TagViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\Be\TagViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\CategoryViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\CategoryViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\PostViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\PostViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\Socials\MastodonViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\Socials\MastodonViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Link\TagViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Link\TagViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Schema\BlogPostingViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Schema\BlogPostingViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Schema\PersonViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Schema\PersonViewHelper',
    'T3G\AgencyPack\Blog\ViewHelpers\Uri\AvatarViewHelper' => 'WapplerSystems\Blog\ViewHelpers\Uri\AvatarViewHelper',
];
