services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\Blog\:
    resource: '../Classes/*'

  WapplerSystems\Blog\Domain\Factory\CommentFormFactory:
    public: true

  WapplerSystems\Blog\Domain\Factory\FrontendUserCommentFormFactory:
    public: true
    shared: false


  WapplerSystems\Blog\Listener\RenderAdditionalContentToRecordList:
    tags:
      - name: event.listener
        identifier: 't3g/blog/render-additional-content-to-record-list'

  WapplerSystems\Blog\Listener\ModifyPageLayoutContent:
    tags:
      - name: event.listener
        identifier: 't3g/blog/modify-page-module-content'

  WapplerSystems\Blog\Mail\MailContent:
    public: true

  WapplerSystems\Blog\Service\CacheService:
    public: true

  WapplerSystems\Blog\Service\CommentService:
    public: true

  WapplerSystems\Blog\Service\SetupService:
    public: true
